config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/newpass', :to => 'pages#newpass'
  match '/newpassgen', :to => 'pages#newpassgen'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'

  root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <h2 class="title">Últimos Posts</h2>
  <table class="microposts" summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <div id="pagination"><%= will_paginate @feed_items, :previous_label => "Anterior", :next_label => "Siguiente", :id => "pages", :separator => "&nbsp&nbsp" %></div>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= render 'microposts/post', :post => feed_item.content %></span>
    <% if formato(feed_item.content) != "" %>
      <p></p>
      <span>
        <object width="365" height="205">
          <param name="movie" value="<%= formato(feed_item.content) %>?version=3&amp;hl=es_ES&amp;rel=0"></param>
          <param name="allowFullScreen" value="true"></param>
          <param name="allowscriptaccess" value="always"></param>
          <embed src="<%= formato(feed_item.content) %>?version=3&amp;hl=es_ES&amp;rel=0" type="application/x-shockwave-flash" width="365" height="205" allowscriptaccess="always" allowfullscreen="true"></embed>
        </object>
      </span>
      <p></p>
    <% end%>
    <% if foto(feed_item.content) != "" %>
      <p></p>
      <span>
        <img alt="<%= foto(feed_item.content) %>" class="imagen" src="<%= foto(feed_item.content) %>" width="365px" heigth="auto"/>
      </span>
      <p></p>
    <% end%>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if (current_user?(feed_item.user)||current_user.admin?) %>
    <td class="delete">
      <%= link_to "Eliminar", feed_item, :method => :delete, :class => :delete,
                                       :confirm => "¿Estás seguro?",
                                       :title => feed_item.content %>
    </td>
  <% else %>
    <td></td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_paleta.html.erb
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img alt="<%= paleta(color) %>" src="/images/<%= paleta(color) %>.png" />

app/views/shared/_search.html.erb
<%= form_tag "#", :method => 'get' do %>
<div>  
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Buscar", :name => nil %>
  </p>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<% cont=0 %>
<div id="sidebar">
  <div id="sidebar" class="int">
<h2> Siguiendo </h2>

      <% unless @user.following.empty? %>
        <div>
        <% @user.following.each do |user| %>
            <%= link_to gravatar_for(user, :size => 30), user if cont<5 %>
            <% cont+=1 %>
        <% end %>
        <a href="<%= following_user_path(@user) %>"> mas... </a>
        </div>
      <% end %>

  </div>
</div>
<% cont=0 %>
<div id="sidebar">
  <div id="sidebar" class="int">
<h2> Seguidores </h2>

      <% unless @user.followers.empty? %>
        <div>
        <% @user.followers.each do |user| %>
            <%= link_to gravatar_for(user, :size => 30), user if cont<5 %>
            <% cont+=1 %>
        <% end %>
        <a href="<%= followers_user_path(@user) %>"> mas... </a>
        </div>
      <% end %>

  </div>
</div>

app/views/shared/_user_info.html.erb
<% @user ||= current_user %>
<foto>
  <a href="<%= user_path(@user) %>"> 
    <%= gravatar_for @user, :size => 120 %> 
  </a>
</foto>
<h1><%= @user.name %></h1>
<h2><%= pluralize(@user.microposts.count, "post") %></h2>