config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/newpass', :to => 'pages#newpass'
  match '/newpassgen', :to => 'pages#newpassgen'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'

  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h1>Acerca de</h1>
<p>
  Esta aplicación web a sido desarrollada gracias a la ayuda de 
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  bajo el entorno de <a href="http://rubyonrails.org/">Ruby on Rails</a>.
</p>

<p>
  Se puede encontrar el codigo fuente de esta aplicación en 
  <a href="https://github.com/Lschasoy/Rails_Proyect/">Git Hub</a>.
</p>

app/views/pages/contact.html.erb
<h1>Contacto</h1>
<p>
  Para contactar con los responsables de Ruby on Rails Tutorial
  sobre esta aplicación hágalo en <a href="http://railstutorial.org/feedback">la página de feedback</a>.
</p>

app/views/pages/help.html.erb
<div id="help">
  <div id="help" class="int">
    <h1 class="title">Ayuda</h1>
    <div style="clear: both;">&nbsp;</div>
    <div class="entry" align="center">
      <p>
         <b>Cómo registrarse</b><br>
         En la página de inicio, haz click en el botón "Unete ahora!"
         Una vez dentro, introduce la información requerida (Nombre de usuario, contraseña, correo electronico, color para tu página)
      </p>

      <img class="imagen" src="/images/Settings.png" width=300 height="auto" align="middle" alt="pantalla de ajustes">
      <br></br><br></br>
      <p>
         <b>Publicar un micropost</b><br>
         Para publicar un micropost en la página, en el mismo menú de inicio puedes escribir lo que quieras que se publique.
         Cuando esté listo, sólo hay que pulsar el botón postear y aparecerá en tu perfil de usuario para que otros lo vean.
      </p>

      <img class="imagen" src="/images/Microposts.png" width=300 height="auto" align="middle" alt="publicar un micropost">
      <br></br><br></br>
      <p>
         <b>Incluir enlaces de otras páginas</b><br>
         Si quieres publicar un enlace a otra página con noticias o a un vídeo interesante, tan sólo hay que escribir el enlace
         a la página en cuestión dentro del micropost. El hipervínculo a la página se generará automáticamente una vez se haya publicado.
      </p>

      <img class="imagen" src="/images/Video.png" width=400 height="auto" align="middle" alt="añadir enlace de video">
      <img class="imagen" src="/images/Earth.png" width=400 height="auto" align="middle" alt="añadir enlace de imagen">
      <br></br><br></br>

      <p>
         <b>Incluir emoticonos o memes</b><br>
         Para expresar el estado de ánimo por medio de un emoticono en un micropost, tan sólo tienes que poner el código del emoticono
         de forma que al publicarse el micropost, el emoticono se genera automáticamente. Los códigos para emoticonos son los mismos que
         los de otras aplicaciones como Messenger o Facebook.

         Para incluir un meme, se debe escribir el nombre del mismo entre dos puntos y aparecerá publicado cuando el micropost esté
         en la página.
      </p>

      <img class="imagen" src="/images/Memes.png" width=500 height="auto" align="middle" alt="emoticonos y memes">
      <br></br><br></br>
      <p>
         <b>Eliminar un micropost</b><br>
         Si has publicado un micropost que no te haya gustado, puedes borrarlo dándole al botón "Eliminar" al lado del micropost
         publicado, dentro del menú "Perfil".
      </p>

      <img class="imagen" src="/images/Delete.png" width=500 height="auto" align="middle" alt="borrar un micropost">
      <br></br><br></br>

      <p>
         <b>Olvidaste la contraseña?</b><br>
         En caso de que no recuerdes la contraseña, en el menú para iniciar sesión, haz click en "Olvidaste la contraseña?"
         Introduce tu dirección de correo electrónico y se te enviará un link para volver a introducir (o cambiar) tu contraseña.
      </p>

      <img class="imagen" src="/images/Login.png" align="center" width=300 height="auto" align="middle" alt="inicio de sesion">
      <br></br><br></br>
      <p>
         <b>Cómo seguir a otro usuario</b><br>
         Para seguir a otro usuario y poder ver sus microposts, ve al menú Usuarios, donde aparece la lista de los usuarios registrados
         actualmente en la página. Entra en la página del usuario al que vas a seguir y haz click en el botón "Seguir".
         Si deseas seguir a un usuario en concreto y no lo ves en la lista, tan sólo tienes que introducir su nombre en la barra de
         búsqueda. Si hay un usuario con ese nombre, podrás seguirlo.

         Si te has cansado de seguir a un usuario, sólo tienes que dirigirte a la página del mismo (como se hizo para seguirle) y
         darle al botón "Dejar de seguir".
      </p>

      <img class="imagen" src="/images/Follow.png" width=300 height="auto" align="middle" alt="seguir a otro usuario">
      <img class="imagen" src="/images/Unfollow.png" width=200 height="auto" align="middle" alt="dejar de seguir a otro usuario">
      <br></br><br></br>
      <p>
         <b>Cómo cambiar los ajustes del perfil</b><br>
         Para cambiar los ajustes del perfil (un nuevo nombre de usuario, cambiar el correo electrónico o la contraseña), sólo hay que
         hacer click en el menú Ajustes, y realizar allí los cambios que se deseen.
     </p>
      <br></br><br></br>
      <p>
         <b>Cómo cambiar la foto de perfil</b><br>
         Tu foto de perfil es aquella que aparece en la página de Gravatar, que se enlaza con tu perfil de usuario.
         Para modificar la foto, dirígete a tu perfil de Gravatar y escoge una nueva imagen.
      </p>

      <p>

      </p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% if signed_in? %>

<div id="content">
<div id="content" class="int">
  <div summary="Para usuarios conectados" class="home">

        <h1 class="title">¿Que hay de nuevo?
        <%= render 'shared/micropost_form' %>
        </h1> 
        <%= render 'shared/feed' %>
      
  </div>
  <div style="clear: both;">&nbsp;</div>
</div>
</div>
<div id="side">
<div id="sidebar">
  <div id="sidebar" class="int">
      <%= render 'shared/user_info' %>
  </div>
</div>

      <%= render 'shared/stats' %>

</div>


<% else %>

  <div id="home">
    <div class="text">
      <h1>Bienvenidos a Micropost</h1>
      <p>
        Únete a la comunidad de 
        <a href="#">Micropost</a>
        y comparte con tus amigos lo que quieras.
      </p>
      <table class="tabla">
        <tr>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td>     
            <%= link_to "Únete ahora!", signup_path, :class => "signup_button round" %>
          </td>     
          <td>
            <%= link_to "Iniciar sesión", signin_path, :class => "signup_button round" %>
          </td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        </tr>
      </table>    
    </div>
  </div>

<% end %>

app/views/pages/newpass.html.erb
<div id="singin">
  <div id="signin" class="int">
    <h1>Cambio de contraseña</h1>
    <%= form_for(@email) do |f| %>
      <p>
        Introduzca su dirección de correo electrónico
      </p>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </div>
      <div class="actions">
        <%= f.submit "Entrar" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/newpassgen.html.erb
<h1>Se ha cambiado la contraseña</h1>
<p>
  Se ha generado una nueva contraseña para usted. La nueva contraseña ha sido enviada
  a la dirección de correo electrónico facilitada. 
</p>
<p>
  Compruebe su bandeja de entrada y vuelva a iniciar sesión con la nueva contraseña.
</p>