config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/newpass', :to => 'pages#newpass'
  match '/newpassgen', :to => 'pages#newpassgen'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer">
    <div>
        <p>
	Esta aplicación ha sido desarrollada gracias al libro y tutorial de 
	<a href="http://ruby.railstutorial.org/chapters/">Rails Tutorial</a>.
        </p>
	<p>Copyright (c) 2012 <a href="http://www.ull.es/"> Universidad de La Laguna</a>. All rights reserved. Designed by <a href="http://www.freecsstemplates.org/"> Free CSS Templates</a>.</p>
    </div>
    <div>
      <p>
        <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fpure-galaxy-5966.herokuapp.com%2F"><img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a>
        <a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="¡CSS Válido!" /></a> 
        <a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="¡CSS Válido!" /></a>
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="header-wrapper">
  <div id="header">
    <div id="logo">
      <% logo = image_tag("pajarito.png", :alt => "Micropost app", :class => "round") %>
      <%= link_to logo, root_path %>
    </div>
    <div id="menu">
      <ul>
	<li><%= link_to "Inicio", root_path %></li>
	<li><%= link_to "Ayuda", help_path %></li>
	<% if signed_in? %>
	  <li><%= link_to "Usuarios", users_path %></li>
	  <li><%= link_to "Perfil", current_user %></li>
	  <li><%= link_to "Ajustes", edit_user_path(current_user) %></li>
	  <li><%= link_to "Salir", signout_path, :method => :delete %></li>
	<% else %>
	  <li><%= link_to "Entrar", signin_path %></li>
	<% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!-- <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> -->
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<% @user = current_user %>
<link href="<%= stylesheet(@user) %>" rel="stylesheet" type="text/css" />
<script src="/javascripts/search.js" type="text/javascript"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
      <%= render 'layouts/header' %>

      <div id="page">
	<div id="page-bgtop">

	      <% flash.each do |key, value| %>
		<div class="flash <%= key %>"><%= value %></div>
	      <% end %>
	      <%= yield %>
	    
	</div>
      </div>
      <div style="clear: both;">&nbsp;</div>
      <%= render 'layouts/footer' %>
  </body>
</html>